### ISSUE TITLE
Add resource provider for new S3-compatible object storage

### ISSUE THREAD

**Issue by zejji** [UpCloudLtd/terraform-provider-upcloud#101]
Unless I am missing something, it does not yet appear to be possible to create S3-compatible object storage instances using the Upcloud Terraform provider.

Could this feature be added to the provider?

**Comment by mlaitinen** [comment]
Related PR: #124

**Comment by mlaitinen** [comment]
The PR was merged, so I think this issue should be closed.

Example here: https://github.com/UpCloudLtd/terraform-provider-upcloud/blob/master/examples/object_storage.tf
