### ISSUE TITLE
Provider runtime panic: index out of range [1] with length 1

### ISSUE THREAD

**Issue by rkrzr** [UpCloudLtd/terraform-provider-upcloud#106]
I am running into a runtime error, thrown by the upcloud TF provider, when running `terraform plan`:

```
> terraform plan
upcloud_server.bla: Refreshing state... [id=asdf]

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: index out of range [1] with length 1
```

The error message unfortunately does not indicate where this error is being thrown exactly.

## Context

I earlier was able to use this provider successfully to provision a new UpCloud server via TF.
Both `terraform plan` and `terraform apply` worked without a problem.

However, when I now run `terraform plan` again it fails every time with the error above. There have been no changes to my TF definitions. I am setting `UPCLOUD_USERNAME` and `UPCLOUD_PASSWORD` as env vars.

I have also tried removing `.terraform` and re-running `terraform init`, but that did not solve the problem.

TF version: 0.14.3
UpCloud provider version: 1.0.0

Is there a way to pinpoint where this error is being thrown?
(I looked through `crash.log` but couldn't find anything helpful)

**Comment by tohalla** [comment]
Hello,

Likely that this is due to changes done to the server storage somewhere else (e.g. detaching storage from the control panel). Currently the provider fails to sync with changes done elsewhere. This is something we aim to fix before the next release.

**Comment by tohalla** [comment]
should not face the issue anymore with the release of 2.0.0
