### ISSUE TITLE
Improve workflow for tags

### ISSUE THREAD

**Issue by zejji** [UpCloudLtd/terraform-provider-upcloud#108]
While there is an "upcloud_tag" resource as described [here](https://registry.terraform.io/providers/UpCloudLtd/upcloud/latest/docs/resources/upcloud_tag), it is not currently possible to easily create a new server and add tags to it without affecting the tags attached to other servers. In fact, the current implementation of tags is virtually useless for real-world usage.

Specifically, it would be helpful to be able create a server with a given set of tags like this:
```
resource "upcloud_server" "example" {
  # ... other configuration ...

  tags = [ "docker", "linux", "webservers" ]
}
```

The reason for this is that generally one wants to create a server and add tags at the same time, without making changes to any other servers.

Compare e.g. the AWS Terraform documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#getting-started-with-resource-tags).

**Comment by mkhq** [comment]
Agree with above, it would simplify the usage of tags significantly if it would be available inside the server definition.
