### ISSUE TITLE
Template setting up firewall disables firewall

### ISSUE THREAD

**Issue by bbros-dev** [UpCloudLtd/terraform-provider-upcloud#145]
I've finally tracked this down to this terraform provider.

Whenever `terraform apply` results in the instance restarting the firewall is turned back off.
This prevents scripts run after `terraform apply` from accessing the instance.

We have to go into the account pages to activate the firewall functionality.

**Comment by kaminek** [comment]
Hello @bbros-dev can you add some context please? the terraform file content

**Comment by bbros-dev** [comment]
Unfortunately we can't share anything from this code base - commercial restrictions.
Your integration tests for this scenario are obviously green.

Can you point to the test?

We might be able to work what we have done wrong, or t least point out how our use case differs from your test.

**Comment by kaminek** [comment]
Hi @bbros-dev,
We tested the current version v2.0.0 and indeed this is a bug, we have fixed it in the meantime. We ll release a new version soon.
