### ISSUE TITLE
Error with terraform 0.12

### ISSUE THREAD

**Issue by jawabuu** [UpCloudLtd/terraform-provider-upcloud#147]
Following your README with this minimal example;

```
provider "upcloud" {
  # Your UpCloud credentials are read from the environment variables:
  # export UPCLOUD_USERNAME="Username of your UpCloud API user"
  # export UPCLOUD_PASSWORD="Password of your UpCloud API user"
  version = "~> 2.0"
}
```

```
$ terraform version
Terraform v0.12.29
```
```
$ terraform providers
.
└── provider.upcloud 2.0.0
```
```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "upcloud" not available for installation.

A provider named "upcloud" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/windows_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```

An error is thrown.
@tohalla @vtorhonen

**Comment by Darep** [comment]
If I remember correctly, with Terraform 0.12, you need to build the provider locally first (see https://github.com/UpCloudLtd/terraform-provider-upcloud/blob/master/README.md#consuming-local-provider-with-terraform-0120) and cannot use the `version`-attribute inside `provider`.

README needs to be updated with this information…

**Comment by Darep** [comment]
I've created MR to update README here: https://github.com/UpCloudLtd/terraform-provider-upcloud/pull/148

Hopefully someone can review it :P

**Comment by jawabuu** [comment]
Thanks @Darep 
Would it be possible to publish upcloud provider at least in `0.12.26` so it doesn't require local build?

**Comment by kaminek** [comment]
Hi @jawabuu,
We unfortunately cannot maintain a terraform version < 0.12, as it's set in the [requirement](https://github.com/UpCloudLtd/terraform-provider-upcloud#requirements)
