### ISSUE TITLE
Attaching SDN network to existing machine calls in for "force replacement"

### ISSUE THREAD

**Issue by villelamminen** [UpCloudLtd/terraform-provider-upcloud#183]
Attaching SDN network to existing machine can be done from UpCloud Hub, but Terraform calls in for "force replacement". This would unnecessarily destroy and recreating the machine.

**Comment by peknur** [comment]
Hi @villelamminen!

Thank you for reporting this and sorry for late response. With our latest version 2.7.1 you should be able to modify network interfaces without recreating the server.

**Comment by thevilledev** [comment]
Fix available and no further comments, so I will go ahead and close off the issue. Feel free to reach out if you're still experiencing these issues!
