### ISSUE TITLE
Long hostname breaks creation of upcloud_server resource

### ISSUE THREAD

**Issue by pedro-mm-pereira** [UpCloudLtd/terraform-provider-upcloud#190]
When creating an upcloud_server resource while setting an hostname that is valid but long I get the following error:
The attribute title has an invalid value. (SERVER_TITLE_INVALID)

For what I can see in the [source code](https://github.com/UpCloudLtd/terraform-provider-upcloud/blob/b8e4b86/upcloud/resource_upcloud_server.go) it seems that hostname is allowed to have 128 chars but the title that is formed from hostname + " (managed by terraform)" is only allowed to have 64 chars.

Is it possible to truncate the title instead of having it erroring? Or give an option to set it on resource creation instead of having it computed?

**Comment by Darep** [comment]
This has now been fixed in 2.1.3! Please give it a go and let us know if you have any problems 😊

**Comment by pedro-mm-pereira** [comment]
I can confirm the fix is working.
Many many thanks @Darep
