### ISSUE TITLE
Feature request: managed database public host & port as attributes

### ISSUE THREAD

**Issue by mlaitinen** [UpCloudLtd/terraform-provider-upcloud#214]
Just tried the `upcloud_managed_database_postgresql` resource for the first time and I'm stoked about it!

I'm trying to create a new role in the database using the [cyrilgdn/postgresql](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest) provider, but I can't use the private endpoint for that.

It would be really useful to have attributes `service_host_public` and `service_port_public` in addition to the current private attributes.

**Comment by vtorhonen** [comment]
Hey @mlaitinen, thanks for reaching out :) You can control these settings through the `properties` attribute like this:

```
resource "upcloud_managed_database_postgresql" "pg1" {
  name = "pg1"
  plan = "1x1xCPU-2GB-25GB"
  zone = "fi-hel1"

  properties {
    public_access = true
    ip_filter     = ["a.b.c.d/32"]
  }
}
```

Full documentation on all available properties is [here](https://github.com/UpCloudLtd/terraform-provider-upcloud/blob/master/docs/resources/managed_database_postgresql.md#nested-schema-for-properties).

And here's how you can access the endpoint details for example as a Terraform module output:

```
output "upcloud_managed_database_public_host" {
  value       = [for c in upcloud_managed_database_postgresql.pg1.components : c if c.route == "public" && c.component == "pg"][0].host
  description = "Public hostname"
}

output "upcloud_managed_database_public_port" {
  value       = [for c in upcloud_managed_database_postgresql.pg1.components : c if c.route == "public" && c.component == "pg"][0].port
  description = "Public port"
}
```

**Comment by mlaitinen** [comment]
Oh, great! Thank you.
