### ISSUE TITLE
Submitting non valid values as updates succeeds

### ISSUE THREAD

**Issue by LordChocoBlizzBallz** [UpCloudLtd/terraform-provider-upcloud#23]
Example:

```

  storage_devices = [
    {
      size    = 70
      action  = "clone"
      storage = "Ubuntu Server 16.04 LTS (Xenial Xerus)"
      title   = "Storage 1"
      tier    = "asdsds"
    },
  ]
```

Results correctly in:

```
Error: Error applying plan:

1 error(s) occurred:

* upcloud_server.test: 1 error(s) occurred:

* upcloud_server.test: The attribute tier has an invalid value. (TIER_INVALID)
```

But after creating this resource successfully and then updating with the incorrect 

`tier    = "asdsds"`

Results in an apparent success(no error messages).

**Comment by cancerballs** [comment]
The reason for this is that Tier is not a mutable value and is not being sent for the update.

**Comment by PopoSensei** [comment]
This has been fixed in the latest master version, which will be a release v.0.1.0. Storage Tier is expected to be either hdd or maxiops. Provider will throw an error to user trying invalid storage tier: `Error: expected storage_devices.0.tier to be one of [hdd maxiops], got asdsds`
