### ISSUE TITLE
How to assing multiple IPv4 & IPv6 addresses to a server

### ISSUE THREAD

**Issue by LordChocoBlizzBallz** [UpCloudLtd/terraform-provider-upcloud#24]
How does one set multiple IPv4 and IPv6 addresses to a single server?

**Comment by PopoSensei** [comment]
in the new release of Terraform Provider we have added network interfaces and floating IP:s as resources. So now there are multiple ways to set multiple IP:s. Both are documented in the provider using `make website` and moving to [http://localhost:4567/docs/providers/upcloud](http://localhost:4567/docs/providers/upcloud)
