### ISSUE TITLE
Load balancer proxy protocol

### ISSUE THREAD

**Issue by robinAwallace** [UpCloudLtd/terraform-provider-upcloud#271]
I see from Upcloud hub that it is possible to enable proxy protocol for load balances frontend. But it seems not possible to do from terraform.

**Comment by ka-myl** [comment]
Hi @robinAwallace, this is now available in v2.5.0 in `properties` block.

```
resource "upcloud_loadbalancer_frontend" "lb_fe_1" {
  # your regular frontend attributes

  properties {
    timeout_client                 = 20
    inbound_proxy_protocol = true
  }
}
```

I will close this issue for now, let us know if you have any problems with this.
