### ISSUE TITLE
API limitation doesn't meet platform one

### ISSUE THREAD

**Issue by leorimmer** [UpCloudLtd/terraform-provider-upcloud#296]
https://github.com/UpCloudLtd/terraform-provider-upcloud/blob/7d02c3698c2ed56e3c97c015701256c875e056f2/internal/service/storage/storage.go#L39

Drive should has more extended range of available Gigabytes since you can extend 2048GB+ it from UI.

**Comment by peknur** [comment]
Hi @leorimmer ! 

Thank for reporting this. We have now fixed this (#297) and new range is available in the next release.
