### ISSUE TITLE
Documentation: accepted values for functions

### ISSUE THREAD

**Issue by F-WRunTime** [UpCloudLtd/terraform-provider-upcloud#306]
It would be nice in [the provided docs ](https://registry.terraform.io/providers/UpCloudLtd/upcloud/latest/docs/data-sources/zones#schema)
There was a reference of what the acceptable values are . 
strings for zone definitions. 
plan values and more 

Love the auto generation though.

**Comment by thevilledev** [comment]
Fixed by #372 and #374. Will be part of the next release.
