### ISSUE TITLE
Firewall rule `position` required but not caught in `plan`

### ISSUE THREAD

**Issue by Johannestegner** [UpCloudLtd/terraform-provider-upcloud#32]
When creating a new firewall rule through the API the `position` argument is optional (in the documentation that is), the same seems to apply for the `terraform plan` command but not for the `terraform apply` command.  

The position field is used when querying for the rules upon removal or updates, which makes it understandable that they require it, but it would be great if the `plan` command threw errors too!

**Comment by iler** [comment]
The fix is now merged. Thanks 👍
