### ISSUE TITLE
Daily backups plan missing

### ISSUE THREAD

**Issue by kidmis** [UpCloudLtd/terraform-provider-upcloud#344]
Hello Team,

There is missing new **daily** backups plan in `simple_backup` schema in `upcloud_server` provider. For now server simple plan includes one daily backup for free, but TF provider doesn't have it. And reports error if I add it in the manifest file.
I've checked API documentation and it's there already, so could you please add it to provider as soon as possible.

API documentation (**API v. 1.3.25, updated 10th of January 2023**):
![IMG_27_01_2023_044318](https://user-images.githubusercontent.com/10752184/215113973-9316e209-2953-4b82-afaa-778adf3ca147.png)

TF provider error (**provider version 2.8.1**):
![IMG_27_01_2023_044655](https://user-images.githubusercontent.com/10752184/215114837-d73a78cc-ac1f-4a77-bcfd-883b5734cf1b.png)

P.S:  **Terraform v1.3.7**

**Comment by kangasta** [comment]
Hi! Thanks for reporting this, we will add support for this soon!

**Comment by kangasta** [comment]
Support for `daily` simple backup plan is added in [v2.8.2](https://github.com/UpCloudLtd/terraform-provider-upcloud/releases/tag/v2.8.2) that should be available for install in a moment.
