### ISSUE TITLE
Resizing a disk succeeds when it should fail

### ISSUE THREAD

**Issue by ilijamt** [UpCloudLtd/terraform-provider-upcloud#38]
If you have a disk that is 24GB and you put 8GB in the definition it says it's success but it should fail, as it's not possible to downsize a disk. 

Latest terraform plugin (built from master today)

Shouldn't this throw an error?

```
    {
      action  = "create"
      size    = 24
      address = "virtio:1"
      tier    = "maxiops"
    },
```

And then after creation change to 

```
    {
      action  = "create"
      size    = 8
      address = "virtio:1"
      tier    = "maxiops"
    },
```

This will succeed sometimes, and sometimes it will give a timeout.
But the disk will remain 24GB.

Removing it from the tf file and then re-adding it with the correct size works properly

**Comment by Johannestegner** [comment]
Is this on a storage resource or as a part of the server resource?

**Comment by cancerballs** [comment]
Fixed in https://github.com/UpCloudLtd/terraform-provider-upcloud/pull/43 #
