### ISSUE TITLE
Environment variables UPCLOUD_USERNAME and UPCLOUD_PASSWORD not working

### ISSUE THREAD

**Issue by Versa78** [UpCloudLtd/terraform-provider-upcloud#394]
Hi,

I'm just getting started using terraform and upcloud. I have a working example where I define username and password in main.tf - provider "upcloud" section.

When I remove username and password from the provider section and set UPCLOUD_USERNAME/UPCLOUD_PASSWORD using export (confirmed with printenv) I get an authorization error.

Failed to get account, error was AUTHENTICATION_FAILED: 'Authentication failed using the given username and password.'. Sometimes I get a 429 - Too many requests, which I think is because the call is getting viewed as unauthorized and throttled.

I am using version 2.11.0

**Comment by villevsv-upcloud** [comment]
Hi, and thanks for reaching out.

We are not able to replicate the issue with environmental variables in our tests, so I would suggest trying out the following procedures:

1. Test by setting the environmental variables inline with the desired terraform command. Overriding the env this way would narrow the problem to your shell env. Using single quotes would also make sure that shell won't expand the contents of the variable value, in case there are special characters it can try to interpret.

```shell
UPCLOUD_USERNAME='your-username' UPCLOUD_PASSWORD='your-password' terraform plan
```

2. Print out the `UPCLOUD_USERNAME` and `UPCLOUD_PASSWORD` environmental variables into a local file within terraform using a null resource. You can then see the contents of the file with `cat upcloud.tmp`. If the values are not present there, or have erratic values, it would also point to an issue with your shell env. Instead, if the values do appear in the `upcloud.tmp` file we need to investigate further if there is something going wrong in our environmental variable reads. In that case, we would need to know which shell (and version) you are using.

```terraform
terraform {
  required_providers {
    upcloud = {
      source  = "UpCloudLtd/upcloud"
      version = "~> 2.0"
    }
  }
}

provider "upcloud" {}

# Null resource that will print the contents of UPCLOUD_USERNAME and UPCLOUD_PASSWORD into a file.
resource "null_resource" "print_credentials_to_file" {
  # trigger to be run on each apply by timestamp
  triggers = { always_run = timestamp() }
  provisioner "local-exec" {
    command = <<-EOT
      # print username to `upcloud.tmp`
      echo "UPCLOUD_USERNAME: $UPCLOUD_USERNAME" > upcloud.tmp
      # print password to `upcloud.tmp`
      echo "UPCLOUD_PASSWORD: $UPCLOUD_PASSWORD" >> upcloud.tmp
    EOT
  }
}
```

**Comment by Versa78** [comment]
Hello and thanks for the quick reply. I found the error and it was not within Upclouds terraform module. Problem solved :) Thanks again!

**Comment by villevsv-upcloud** [comment]
Thank you for the follow-up information. :) I'll close the issue now.
