### ISSUE TITLE
Shutting down the machines when creating a backup policy

### ISSUE THREAD

**Issue by ilijamt** [UpCloudLtd/terraform-provider-upcloud#41]
Is it possible to set the backup policies without shutting down the server ?
Currently whenever I need to add a backup policy the plugin shut downs the servers in question 

Also from the UI looks like it's impossible to set different retention period for disks.
1. Disk0 is the root disk backup daily and keep 1 backup
2. Disk1 is the data disk and backup daily and keep for 1 week
 
But from the terraform plugin it's possible, will this break some functionality, should I be even doing this then?

**Comment by cancerballs** [comment]
1. Yes it's possible to PUT backup_rule modifications to a storage without shutting down the server with the API. The current TF provider code is not optimal. It shuts down the server when modifications are made, any modifications at all and there is no granular control depending on the modifications. This issue should concern itself with the granular control of server shut downs depending of the required modification.

Is this important for your use cases?

2. It's a bug in the current UI and it's in the backlog.

With TF or using the API it's possible to set different retention periods. TF example:

`  storage_devices = [
  {
      # You can use both storage template names and UUIDs
      size    = 50
      action  = "clone"
      tier    = "maxiops"
      storage = "01000000-0000-4000-8000-000020040100"

      backup_rule = {
        interval = "daily"
        time = "0100"
        retention = 8
      }
  },
  {
      # You can use both storage template names and UUIDs
      size    = 30
      action  = "create"
      tier    = "maxiops"

      backup_rule = {
        interval = "mon"
        time = "0000"
        retention = 7
      }
  },
]`

**Comment by ilijamt** [comment]
I know, but currently there is no way to set a backup policy with terraform without shutting down the server?

**Comment by cancerballs** [comment]
Correct.
