### ISSUE TITLE
Storage image update failed

### ISSUE THREAD

**Issue by nikohaap** [UpCloudLtd/terraform-provider-upcloud#46]
There's no effect if the storage id is changed afterwards.
The problem occurs if the original image is tried to change e.g. from Debian GNU/Linux 9.5 (Stretch) to a custom image (e.g. created by the packer)

**Example from the Terraform plan:**
<pre>
$ terraform plan
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.upcloud_server.instance
      storage_devices.0.storage: "01000000-0000-4000-8000-000020040100" => "xxxxxxx-xxxx-xxx-xxx-xxxxxxx"

Plan: 0 to add, 1 to change, 0 to destroy.
</pre>

I think that instead of the update process (`update in-place`)  provider should destroy the current instance and then create a replacement instance with the updated image (`-/+ destroy and then create replacement`)

The result of the terraform plan would look like `Plan: 1 to add, 0 to change, 1 to destroy.`

**Comment by cancerballs** [comment]
Thanks for creating the issue. 

Can you post the .tf file to help me repeat the bug.

**Comment by nikohaap** [comment]
Here's a quick example

<pre>
01-server.tf

provider "upcloud" {
  # You need to set UpCloud credentials in shell environment variable
  # using .bashrc, .zshrc or similar
  # export UPCLOUD_USERNAME="Username for Upcloud API user"
  # export UPCLOUD_PASSWORD="Password for Upcloud API user"
}

resource "upcloud_server" "example-intra" {
  zone     = "fi-hel2"
  hostname = "examle.terraform.testing"

  # Login details
  login {
    user = "tf"

	keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYn6VuEgiH3//qpSa/b3Khrjy3Z4Q4fvvhRNRDrZaJqddLvQLCtoL2ktoke7+0jTcR4Vydi8bk8csUQlZxpWC6SIfif+tB8HjwusbUfLT5I5fJEI/O7gtktvtWkK4GnePFXYIdgKlXKRJ92xFnNOGV+el2zug78QahsrzsyV0Cucfjb7twPyojh5iPl3gf6f7NBHVnsqNELhJqmpo4uY+vSTfHx0siyIGP0U/Jz9dB64kbnoG6GL2fh3CEQ950Ll2luY/cfX52SO+WX/nl156A2VVCozkOSE3wbZ501Gd1508KY7ctuaqOue4DF8ZuQ1uzv4Lf9sfg4Bv4jBMTu4tvB",]

    create_password   = true
    password_delivery = "email"
  }

  storage_devices = [
    {
      # You can use both storage template names and UUIDs
      size    = "30"
      action  = "clone"
      storage = "01000000-0000-4000-8000-000020040100"
      tier = "maxiops"

    },
  ]
}

output "example ipv4_address" {
  value = "${upcloud_server.example-intra.ipv4_address}"
}
</pre>

`$ terraform plan/apply`

Than update the storage id 

<pre>
01-server.tf

provider "upcloud" {
  # You need to set UpCloud credentials in shell environment variable
  # using .bashrc, .zshrc or similar
  # export UPCLOUD_USERNAME="Username for Upcloud API user"
  # export UPCLOUD_PASSWORD="Password for Upcloud API user"
}

resource "upcloud_server" "example-intra" {
  zone     = "fi-hel2"
  hostname = "examle.terraform.testing"

  # Login details
  login {
    user = "tf"

	keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYn6VuEgiH3//qpSa/b3Khrjy3Z4Q4fvvhRNRDrZaJqddLvQLCtoL2ktoke7+0jTcR4Vydi8bk8csUQlZxpWC6SIfif+tB8HjwusbUfLT5I5fJEI/O7gtktvtWkK4GnePFXYIdgKlXKRJ92xFnNOGV+el2zug78QahsrzsyV0Cucfjb7twPyojh5iPl3gf6f7NBHVnsqNELhJqmpo4uY+vSTfHx0siyIGP0U/Jz9dB64kbnoG6GL2fh3CEQ950Ll2luY/cfX52SO+WX/nl156A2VVCozkOSE3wbZ501Gd1508KY7ctuaqOue4DF8ZuQ1uzv4Lf9sfg4Bv4jBMTu4tvB",]

    create_password   = true
    password_delivery = "email"
  }

  storage_devices = [
    {
      # You can use both storage template names and UUIDs
      size    = "30"
      action  = "clone"
      storage = "01000000-0000-4000-8000-000030040101"
      tier = "maxiops"

    },
  ]
}

output "example ipv4_address" {
  value = "${upcloud_server.example-intra.ipv4_address}"
}
</pre>

Only the `upcloud_server.example-intra.storage_devides.storage` has been changed from the  debian stretch to ubuntu

**Comment by nikohaap** [comment]
Hi,
Is there any news about this?

**Comment by cancerballs** [comment]
I'm working on a solution that allows changing from public to private or from private to private template(image).

**Comment by PopoSensei** [comment]
With the current update, that will be release v.0.1.0, this use case will be supported, and the resource will be destroyed and a new replacement will be created. Result of apply executed: `Apply complete! Resources: 1 added, 0 changed, 1 destroyed.`
