### ISSUE TITLE
Terraform timeout problem

### ISSUE THREAD

**Issue by nikohaap** [UpCloudLtd/terraform-provider-upcloud#50]
Hi,

I was trying to create 10  instances (by using the count indexes) at once but the Terraform gave me this kinds of errors:
```
* upcloud_server.instance.2: Timeout reached while waiting for server to enter state "started"
```
Based on that it would be nice to have a timeout feature into the `upcloud_server` resource which makes possible to manage timeouts and functionality in different use cases (delete, update, recreate etc.).

Or is it possible to use connection block inside of the resource like it can be used with the provisioners?

**Comment by cancerballs** [comment]
Can you paste the TF file and crash log and I will investigate this.

**Comment by nikohaap** [comment]
Terraform doesn't crash but it gives some errors.

I was capable to repeat the issue with this .tf file

```
provider "upcloud" {
  # You need to set UpCloud credentials in shell environment variable
  # using .bashrc, .zshrc or similar
  # export UPCLOUD_USERNAME="Username for Upcloud API user"
  # export UPCLOUD_PASSWORD="Password for Upcloud API user"
}

resource "upcloud_server" "test" {
  count    = 10
  zone     = "nl-lia1"
  hostname = "nikoh-timeout-testing-${format("%04d", count.index + 1)}"

  cpu      = "2"
  mem      = "1024"

  # Login details
  login {
    user = "tf"

    keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZNKVSnDL5B+0DwqO04aQLmPKSy55kZ4vDNsKl2/YrI4qroICjWT0Hum89FuHv5HdEmpjWKRpyn06WLIi28C22LO5xDWUbnbsoNSiaNSC/CgKwZ/hu5fmScb0dAf+Va+KS42FEOGcSbAd36R2htRHnaLg4cgN2RjjQw8p5lfiVPl4zDtZr8+mZZKKPs6pxHY54mM5oTt+mqzfncwvnfF4tS498VY5kC4stqZAO1/A3rdP2YI7uIXP2bvQ4MSKohI9eoePTbuOCCZC7E20NA4uKxCeimGCciAusolp+1TrkDBmARF7ew/AI/X/R9d+tlZhcJ1QSx+oM9xhEuGEL6bxJ terraform@lianatech.com",
    ]

    create_password   = false
    password_delivery = "email"
  }

  storage_devices = [
    {
      # You can use both storage template names and UUIDs
      size    = 10
      action  = "clone"
      tier    = "maxiops"
      storage = "01000000-0000-4000-8000-000020040100"
    }
  ]
}
```

**Comment by cancerballs** [comment]
After reviewing this in different zones I think best option is to keep it simple and increase the API time out. This ought to take care of all situations, if not, I can later add functionality for setting timeout in ENV variable.

https://github.com/UpCloudLtd/terraform-provider-upcloud/pull/52
