### ISSUE TITLE
Feature request: support to create a custom image via terraform 

### ISSUE THREAD

**Issue by james-monio** [UpCloudLtd/terraform-provider-upcloud#558]
I'd like to fully automate a server deployment with a custom image through terraform:
1. uploading the image to a storage device
2. creating a custom image resource from a storage device
3. creating a server running the custom image.

Today, steps 1 and 3 are possible through terraform, but step 2 is missing from the provider.  The corresponding command for this in the upcloud cli is `upctl storage templatise`, I believe.

Also, I think ideally a custom image would be a separate terraform resource from the upcloud_storage resource, even though the image seems to be backed by a storage device.

**Comment by kangasta** [comment]
Thank you for the feature request! [upcloud_storage_template](https://registry.terraform.io/providers/UpCloudLtd/upcloud/latest/docs/resources/storage_template) is now available in [v5.10.0](https://github.com/UpCloudLtd/terraform-provider-upcloud/releases/tag/v5.10.0) 🚢
