### ISSUE TITLE
Configurable public networking, like private_networking

### ISSUE THREAD

**Issue by pasikarkkainen** [UpCloudLtd/terraform-provider-upcloud#61]
Looking at the Upcloud API documentation it's possible to configure public and private networking separately for VMs.

Based on https://github.com/UpCloudLtd/terraform-provider-upcloud/tree/master/examples it seems there is an option "private_networking" true/false which sounds like it configures if there's a private network for the VM or not. I need similar configuration option for public networks/IPs..

So it'd be nice to have an option "public_networking" true/false to choose if the VM should get public IP or not..

Basicly I need to be able to provision 3 different kinds of VMs:
- Both the public and private IP.
- Only public IP.
- Only private IP.

Thoughts?

**Comment by PopoSensei** [comment]
Hello,

This is now possible with the current master of the Provider. I'll paste here a snippet from the provider documentation upcloud_server resource, that can be accessed with the `make website` command and Docker.

```
The network_interface block supports:

ip_address_family - (Optional) The IP address type of this interface (one of IPv4 or IPv6).
type - (Required) The type of network interface (one of private, public or utility).
network - (Optional) The unique ID of a network to attach this interface to. Only supported for private interfaces.
source_ip_filtering - (Optional) true if source IPs should be filtered. Only supported for private interfaces.
bootable - (Optional) true if this interface should be used for network booting. Only supported for private interfaces.
In addition to the arguments listed above, the following attributes are exported:

title - A short, informational description.
The network_interface block also exports the following additional attributes:

ip_address - The assigned IP address.
ip_address_floating - true if a floating IP address is attached.
mac_address - The assigned MAC address.
```

So while creating the server you can define network interface that is either private or public. There can be multiple network interfaces per server. For the private interfaces you can define networks in a different resource.

Hope this helps.
