### ISSUE TITLE
enable API seems only be possible in old dashboard

### ISSUE THREAD

**Issue by pjvds** [UpCloudLtd/terraform-provider-upcloud#63]
The upcloud terraform provider depends on the upcloud API being enabled. The only way I've found to enable the API is via the "old" upcloud dashboard:

![image](https://user-images.githubusercontent.com/150387/58547318-6efd8080-8207-11e9-9bc7-cd06f0b8b7e2.png)

Does the new upcloud dashboard support a way to enable API integration?

**Comment by LordChocoBlizzBallz** [comment]
Currently the dashboard allows enabling API only for subaccounts. We are working on providing the  API access checkbox for main account also in the near future, before the old dashboard EOL.

**Comment by PopoSensei** [comment]
The new dashboard supports API access checkbox for main account

<img width="631" alt="Screenshot 2020-09-16 at 11 27 50" src="https://user-images.githubusercontent.com/14196611/93312339-cade8500-f80f-11ea-9265-8ea3e7d3d8e9.png">
