### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by cdvv7788** [UpCloudLtd/terraform-provider-upcloud#64]
I am trying out upcloud, and the terraform provider is important to me. However, it seems to be inactive, recent terraform versions are not supported and several PRs are open. In fact, this year not a single issue has been answered by the mantainers.
Are there any plans for this project?

**Comment by LordChocoBlizzBallz** [comment]
Unfortunately we haven't prioritized the Terraform provider for a while but work is underway for supporting the newest TF version. The plan is to develop and maintain a working and up to date tf provider for UpCloud.
