### ISSUE TITLE
official documentation like on terraform server

### ISSUE THREAD

**Issue by scippio** [UpCloudLtd/terraform-provider-upcloud#66]
Is somewhere official documentation like on terraform server?

**Comment by LordChocoBlizzBallz** [comment]
What do you mean?

**Comment by scippio** [comment]
For example like google: https://www.terraform.io/docs/providers/google/index.html

**Comment by LordChocoBlizzBallz** [comment]
We got examples here https://github.com/UpCloudLtd/terraform-provider-upcloud/tree/master/examples

and more specifically here 

https://github.com/UpCloudLtd/terraform-provider-upcloud/blob/master/examples/01_server.tf

Is there something else you would like to see documented?

**Comment by scippio** [comment]
it's not as clear as on the terraform site, but nevermind... it's fine.
