### ISSUE TITLE
Submit UpCloud provider to Terraform development program

### ISSUE THREAD

**Issue by binaryfire** [UpCloudLtd/terraform-provider-upcloud#70]
Hi guys,

I'm using Terraform Cloud and unfortunately only official providers are supported. Hashicorp told me developers need to join their provider development program to be added as an official provider: 
 https://www.terraform.io/guides/terraform-provider-development-program.html

Would you guys be able to do this so we can use UpCloud with Terraform Cloud?

Cheers

**Comment by stalkerg** [comment]
Same question.

**Comment by isarpila** [comment]
Hi,

Thanks for the feedback. Becoming a verified Terraform provider (https://registry.terraform.io/browse/providers) is on our roadmap and we should receive the status still in 2020.

**Comment by isarpila** [comment]
Hi,

UpCloud's provider can now be found from the verified provider's list:

https://registry.terraform.io/providers/UpCloudLtd/upcloud/latest

**Comment by isarpila** [comment]
Closing this as we are listed as a verified provider status.
