### ISSUE TITLE
Cannot pass username and password in as non-environment variables

### ISSUE THREAD

**Issue by Asmodeusss** [UpCloudLtd/terraform-provider-upcloud#79]
I'm currently using the plugin upcloud provider with terraform 0.13. I do not want to set the username and password as an environment variable, since running it with sudo would require me to type `UPCLOUD_USERNAME=<username> UPCLOUD_PASSWORD=<password> sudo -E terraform apply` every time.

As per 0.13, the plugin is properly built and linked in $HOME/.terraform.d/upcloud.com/upcloud/upcloud/1.0/linux_amd64 and works correctly when initializing, but when running `terraform plan` I get the following error:

```
Error: Missing required argument

The argument "password" is required, but was not set.


Error: Missing required argument

The argument "username" is required, but was not set.
```

the terraform configuration in the main.tf looks like this
```
terraform {
  required_providers {
    upcloud = {
        source = "upcloud.com/upcloud/upcloud"
        username = <username>
        password = <password>
    }
  }
}
```

I've explored the provider.go file and it seemd to indicate a "username" and "password" field as valid options, but so far nothing seems to work.

**Comment by tohalla** [comment]
Hello Asmodeusss,

You are able to provide the credentials via the provider configuration -block with

```tf
provider "upcloud" {
  username = "<username>"
  password = "<password>"
}
```

If you feel uncomfortable using environment variables for storing the credentials, you can have the block in a separate file and leave it outside of the version control.
