### ISSUE TITLE
source_ip_filtering always stuck to true

### ISSUE THREAD

**Issue by malafoss** [UpCloudLtd/terraform-provider-upcloud#86]
Upcloud terraform provider does not let source_ip_filtering to be set to false.

### Steps to reproduce:

Apply the following terraform file:
```
terraform {
  required_providers {
    upcloud = {
      source = "UpCloudLtd/upcloud"
      version = "1.0.0"
    }
  }
}

provider "upcloud" {
}

resource "upcloud_network" "network" {
  name = "my private network"
  zone = "fi-hel1"

  ip_network {
    address = "10.201.0.0/24"
    dhcp = false
    dhcp_default_route = false
    family = "IPv4"
    gateway = "10.201.0.1"
  }
}

resource "upcloud_server" "server" {
  zone = "fi-hel1"
  hostname = "server"
  plan = "1xCPU-1GB"

  storage_devices {
    size = 10
    action = "clone"
    tier = "maxiops"
    title = "boot disk"
    storage = "Debian GNU/Linux 10 (Buster)"
  }

  network_interface {
    type = "private"
    network = upcloud_network.network.id
    source_ip_filtering = false
  }
}

output "source_ip_filtering" {
  value = upcloud_server.server.network_interface[0].source_ip_filtering
}
```

### Expected behaviour:

Should output `source_ip_filtering = false`.

### Actual behaviour:

Incorrectly outputs `source_ip_filtering = true`, which also causes recreation of new instance if another `terraform apply` is made subsequently. Possibly calls to `POST /1.3/server/{uuid}/networking/interface` are not made at all, which also prevents use of static ip addresses.

**Comment by isarpila** [comment]
Hi,

Thanks for the feedback. We were able to reproduce this problem and are working to fix it.

BR,

-Ilkka
