### ISSUE TITLE
CIDR block inputs

### ISSUE THREAD

**Issue by bbros-dev** [UpCloudLtd/terraform-provider-upcloud#87]
**Update:**  We think this can be treated as a documentation issue, where the `source_address_start = cidrhost(var.cidr, "1")` and `source_address_end = cidrhost(var.cidr, "-1")` examples are included in the Terraform registry docs for `upcloud_network` as well as the github docs.

For the same reasons/motivation as in issue #65 : to reuse terraform code across cloud vendors it helps to pass network ranges a cidr blocks instead of:
 
```json
      source_address_end = "192.168.1.255"
      source_address_start = "192.168.1.1"
```

Right now we have to re-write all our resources that abstract away cloud provider specifics, to use different inputs.
This also makes it more costly/difficult to integrate UpCloud when other providers consume `["172.19.48.0/20", "172.19.64.0/20", "172.19.80.0/20",]`.

~~A workaround might be to provide two helper functions that takes as input a CIDR block and outputs either the start IP or end IP.~~

**Comment by bbros-dev** [comment]
The workaround currently exists using Terraform `cidrhost(...)`.
In case anyone else comes along this path, using this `main.tf`:

```hcl
##############################################
# Variables
##############################################
variable "iprange" {
  default = "10.0.0.0/16"
}

variable "hostnum" {
  default = 2
}

##############################################
# Outputs
##############################################
output "ip_output" {
  value = "${cidrhost(var.iprange,var.hostnum)}"
}
```

You can get the start IP:

```bash
$ yes yes | terraform apply -var "iprange=172.16.0.0/20" -var "hostnum=1"
...
ip_output = 172.16.0.1
```

You can get the end IP:

```bash
$ yes yes | terraform apply -var "iprange=172.16.0.0/20" -var "hostnum=-1"
...
ip_output = 172.16.15.255
```

**Comment by isarpila** [comment]
Closing this as we discussed this over email already with you Mike.

regards,

-Ilkka

**Comment by opentokix** [comment]
This is so dumb, just implement CIDR like literally _everybody_else_ 

**Start address and end address is some amateur homelab stuff.**
