### ISSUE TITLE
Invite to publish to the Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [UpCloudLtd/terraform-provider-upcloud#88]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published, since it makes using and installing it much easier for anyone using Terraform 0.13! Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing this provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by PopoSensei** [comment]
Hello @aicarmic I checked the instructions you linked and skipped to the "Publishing to the registry" topic. It seems to me that we are already published according to the website. Or maybe I'm missing something, please let me know.

Thank you,
Team @ UpCloud

**Comment by aicarmic** [comment]
Thanks @PopoSensei double checked and you are indeed published, thanks for that and for your contributions to this provider!!
